spring:
#  security:
#    user:
#      name: admin
#      password: admin
  datasource:
    url: jdbc:h2:file:./askquestiondb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /api/v1/test/h2
springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/test/swagger-ui
  api-docs.path: /api/v1/test/api-docs

askquestion:
  secret:
    key: "YOU WILL NEVER WALK ALONE"
  expires:
    in: 604800